# Generated by Django 2.2.2 on 2021-09-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='タイムスタンプ')),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Blog'},
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='公開日時'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='タグ'),
        ),
    ]
