# Generated by Django 2.2.2 on 2021-09-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': ''},
        ),
    ]
