# Generated by Django 2.2.2 on 2021-09-29 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210929_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
