# Generated by Django 2.2.2 on 2021-09-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210929_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, verbose_name='あらすじ'),
        ),
    ]
