# Generated by Django 2.2.2 on 2021-09-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210929_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=200, verbose_name='あらすじ'),
        ),
    ]
