# Generated by Django 2.2.2 on 2021-09-28 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kazumaru', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Kazumaru'},
        ),
    ]
